// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNX4vZ0139ir0RtDRT8Tn23e1H7Ck5XWo',
    appId: '1:180650842554:web:007d3105224e35bcc16583',
    messagingSenderId: '180650842554',
    projectId: 'flutter-firebase-app-ab2d1',
    authDomain: 'flutter-firebase-app-ab2d1.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-ab2d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVIkDXqcwxYVv27m14-fTFhBYHo5QBvOE',
    appId: '1:180650842554:android:8386d00e16f6232cc16583',
    messagingSenderId: '180650842554',
    projectId: 'flutter-firebase-app-ab2d1',
    storageBucket: 'flutter-firebase-app-ab2d1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlYaQoypKxKMlGti-C1TXalWn-4mbaQgk',
    appId: '1:180650842554:ios:cf50107d869d6905c16583',
    messagingSenderId: '180650842554',
    projectId: 'flutter-firebase-app-ab2d1',
    storageBucket: 'flutter-firebase-app-ab2d1.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlYaQoypKxKMlGti-C1TXalWn-4mbaQgk',
    appId: '1:180650842554:ios:cf50107d869d6905c16583',
    messagingSenderId: '180650842554',
    projectId: 'flutter-firebase-app-ab2d1',
    storageBucket: 'flutter-firebase-app-ab2d1.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNX4vZ0139ir0RtDRT8Tn23e1H7Ck5XWo',
    appId: '1:180650842554:web:0cf5eb53c14e0f5ec16583',
    messagingSenderId: '180650842554',
    projectId: 'flutter-firebase-app-ab2d1',
    authDomain: 'flutter-firebase-app-ab2d1.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-ab2d1.firebasestorage.app',
  );
}
